// <auto-generated />
using System;
using LifeLogger.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LifeLogger.Core.Migrations
{
    [DbContext(typeof(LifeLoggerDbContext))]
    partial class LifeLoggerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LifeLogger.Core.Entity.LoggedItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Duration");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("TagName");

                    b.HasKey("Id");

                    b.HasIndex("TagName");

                    b.ToTable("LoggedItem");
                });

            modelBuilder.Entity("LifeLogger.Core.Entity.Tag", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Name");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("LifeLogger.Core.Entity.LoggedItem", b =>
                {
                    b.HasOne("LifeLogger.Core.Entity.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagName");
                });
#pragma warning restore 612, 618
        }
    }
}
